import * as file from "./file-imports";

let aartiData = [
  {
    number: "1",
    name: "अंबुजदल लोचनी",
    sub: "महापूजेची आरती १ ली ",
    search_txt: [
      "ambujadal lochani",
      "ambujdal",
      "adi shakti narayani",
      "ananta sukha daini",
      "sundaragirinandini",
      "aagamya manamohini",
      "adya kamal lochani",
    ],
    file: file.aartiSangrah1,
  },
  {
    number: "2",
    name: "जय जय हो जगदंबे । भवानी त्रैलोक्ये लोचनी ।",
    sub: "महापूजेची आरती २ री",
    search_txt: [
      "jay jay ho jagadambe bhavani trailoke lochani",
      "aarati ovalu janani",
      "pavasi tu nirvani",
      "jay jay jagadambe",
    ],
    file: file.aartiSangrah2,
  },
  {
    number: "3",
    name: "आरती त्रिपुर सुंदरीची",
    sub: "महापूजेची आरती ३ री",
    search_txt: [
      "aarti tripur sundarichi",
      "amba bai renukechi",
      "ambabai renukechi",
    ],
    file: file.aartiSangrah3,
  },
  {
    number: "4",
    name: "लव मज लागला",
    sub: "महापूजेची आरती ४ थी",
    search_txt: [
      "lav maj lagala",
      "lava maja lagala",
      "bheda bheda kaicha",
      "bedha behd kaicha",
      "aala kantala vishayacha",
      "dhanda mulmayecha",
      "dhanda mul mayecha",
    ],
    file: file.aartiSangrah4,
  },
  {
    number: "5",
    name: "जय जय हो नवचंडे",
    sub: "महापूजेची आरती ५ वी",
    search_txt: [
      "jay jay ho navachande",
      "jay jay ho navchande",
      "tripure chandamunda bal dandhe ho",
      "kali kilmish avakhande",
      "janani ashtadash bujdande ho",
      "jay jay vighna vitande",
      "survar vardayini chamunde ho",
      "shobati kari kodande",
      "sundar girivar kulmartande ho",
    ],
    file: file.aartiSangrah5,
  },
  {
    number: "6",
    name: "जय जय हो जगदंबे। एकविरे रेणुका दुहिते।",
    sub: "महापूजेची आरती शेवटची आरती ",
    search_txt: [
      "jay jay ho jagadambe",
      "jay jay ho jagdambe",
      "ekvire renukaduhite o",
      "ruchikatmaj priyakante",
      "bhargav ramachi dwijmate o",
    ],
    file: file.aartiSangrah6,
  },
  {
    number: "7",
    name: "नेससी तू पिवळा ।",
    sub: "नित्याची आरती १ ली ",
    search_txt: [
      "nesasi tu pivala",
      "patola haar shobe gala",
      "aho manramani",
      "manaramani",
      "amravati vasini",
    ],
    file: file.aartiSangrah7,
  },
  {
    number: "8",
    name: "अमरावती वासिनी ।",
    sub: "नित्याची आरती २ री  ",
    search_txt: [
      "amravati vasini",
      "maj la pav tu nirwani ho",
      "akhanda tujala dhyati",
      "munijan pathati ved purani ho",
    ],
    file: file.aartiSangrah8,
  },
  {
    number: "9",
    name: "दुर्गे दुर्घट भारी ।",
    sub: "दुर्गेची नित्याची आरती ",
    search_txt: ["durge durghat bhari", "tarak sanjivani"],
    file: file.aartiSangrah9,
  },
  {
    number: "10",
    name: "पाहीन मी दर्शना । (भैरवी)",
    sub: "नित्याची भैरवी ",
    search_txt: [
      "pahin mi darshana",
      "pahina me darshana",
      "udho bola udho",
      "udo bola udo",
      "name gondhal",
    ],
    file: file.aartiSangrah10,
  },
  {
    number: "11",
    name: "तुळजाभवानीची आरती। शेवटची आरती (समापन)",
    sub: "तुळजाभवानीची नित्याची शेवटची आरती ",
    search_txt: [
      "tulja ho may raja hi tulja",
      "tulja ho maya raja hi tulja",
      "charani das padle",
      "ambe charani",
      "raja hi tulja",
      "jay jay tulja",
    ],
    file: file.aartiSangrah11,
  },
  {
    number: "12",
    name: "ओवळा ओवळा देवी एकविरामाता ।",
    sub: "एकविरामातेची आरती ",
    search_txt: [
      "oovala ovala devi ekviramata",
      "ovala ovala devi ekwiramata",
      "devi ek viramata",
      "oowala owala devi ekwira mata",
      "tu purvi bhavartha",
    ],
    file: file.aartiSangrah12,
  },
  {
    number: "13",
    name: "अश्विन शुक्लपक्षी",
    sub: "नवरात्रातील आरती १ ली ",
    search_txt: [
      "ashwin shukla pakshi",
      "amba baisali sinhasani ho",
      "pratipade pasuni",
      "ghatasthapana karuni ho",
      "ghatastapana kar ni ho",
      "bramha vishnu mahesh tuze pujan kariti ho",
      "udo mhanava udo amba bai mauli cha ho",
      "udho manava udho ambabai mauli cha ho",
      "anande khelasi kay mahima varnu ticha ho",
      "udho manava udho ambabai maulicha ho",
    ],
    file: file.aartiSangrah13,
  },
  {
    number: "14",
    name: "ॐ जयो जयो माँ जगदम्बे",
    sub: "नवरात्रातील आरती २ री ",
    search_txt: [
      "om jayo jayo maa jagadambe",
      "om jayom jayom ma jagadambe",
      "om jay om jay om ma jagadambe",
      "jay adhya shakti",
      "ma jay aadya shakti",
      "akanda bramhand nipavya",
      "padave pandit ma",
    ],
    file: file.aartiSangrah14,
  },
  {
    number: "15",
    name: "काशी आमुची - प्रथम आरती ",
    sub: "मंगळवारची आरती १ ली ",
    search_txt: [
      "kashi amuchi",
      "kashi amchi",
      "renuka mulapitha naika",
      "je je kalpil te",
      "tu desi iccha purna karisi",
      "mhanavuni prarthana",
      "pave maja dinashi",
      "ahima mahima",
      "balya bugadya shama",
    ],
    file: file.aartiSangrah15,
  },
  {
    number: "16",
    name: "ऐसी आरती होतसे",
    search_txt: [
      "aaisi aarti hot ase",
      "aisi aarti hotase",
      "aise aarti hotase",
      "jana yet ase",
      "jana yetase",
      "sant sajjan koti",
      "deva rishi aale manava aale danava",
      "aho bai cha bheti",
      "aeisi arti hotase jan yetase",
    ],
    file: file.aartiSangrah16,
  },
];

export default aartiData;
